module HTTP2
  CLIENT_PREFACE = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"

  MINIMUM_FRAME_SIZE = 2 ** 14
  MAXIMUM_FRAME_SIZE = 2 ** 24 - 1
  MAXIMUM_WINDOW_SIZE = 2 ** 31 - 1
  PING_FRAME_SIZE = 8
  #RST_STREAM_FRAME_SIZE = 4
  #WINDOW_UPDATE_FRAME_SIZE = 4
end
