module HTTP2
  CLIENT_PREFACE = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"

  MINIMUM_FRAME_SIZE = (2 ** 14).to_i32
  MAXIMUM_FRAME_SIZE = (2 ** 24).to_i32 - 1

  MINIMUM_WINDOW_SIZE = 1
  MAXIMUM_WINDOW_SIZE = (2 ** 31).to_i32 - 1

  PING_FRAME_SIZE = 8
  PRIORITY_FRAME_SIZE = 5
  RST_STREAM_FRAME_SIZE = 4
  WINDOW_UPDATE_FRAME_SIZE = 4

  DEFAULT_HEADER_TABLE_SIZE = 4096
  DEFAULT_ENABLE_PUSH = true
  DEFAULT_INITIAL_WINDOW_SIZE = 65535
  DEFAULT_MAX_FRAME_SIZE = MINIMUM_FRAME_SIZE

  REQUEST_PSEUDO_HEADERS = %w(:method :scheme :authority :path)
  RESPONSE_PSEUDO_HEADERS = %w(:status)
end
